-- HERE I HAVE CREATED THE FOOD BAG DATABASE

CREATE DATABASE food_bag;

-- HERE I HAVE SWITCHED TO USE THE FOOD BAG DATABASE 

USE food_bag;

-- HERE IS I CREATE THEN FOOD TABLE

CREATE TABLE food (
id INT NOT NULL AUTO_INCREMENT,
type VARCHAR(250) NOT NULL,
PRIMARY KEY (id)
);

-- HERE I CREATE THE ADMINS TABLE

CREATE TABLE admins (
id INT NOT NULL AUTO_INCREMENT,
name VARCHAR(250) NOT NULL,
type ENUM ('0','1') NOT NULL,
email_address VARCHAR(250) NOT NULL,
phone_number VARCHAR(50) NOT NULL,
password VARCHAR(250) NOT NULL,
PRIMARY KEY (id)
);

-- HERE I CREATE THE VENDOR TABLE

CREATE TABLE vendor_food (
id INT NOT NULL AUTO_INCREMENT,
admin_id INT NOT NULL,
food_id INT NOT NULL,
name VARCHAR(250) NOT NULL,
amount DECIMAL(20,2) NOT NULL,
PRIMARY KEY (id),
FOREIGN KEY (food_id) REFERENCES food (id),
FOREIGN KEY (admin_id) REFERENCES admins (id)
);

-- HERE I CREATE THE CUSTOMERS TABLE

CREATE TABLE customers (
id INT NOT NULL AUTO_INCREMENT,
name VARCHAR(250) NOT NULL,
phone_number VARCHAR(50) NOT NULL,
address VARCHAR(250) NOT NULL,
payment_method ENUM('card','Mobile Money','Cash'),
PRIMARY kEY (id)
);

-- HERE I CREATE THE ORDERS TABLE LINKED TO CUSTOMERS AND VENDORS

CREATE TABLE orders (
id INT AUTO_INCREMENT,
vendor_id INT,
customer_id INT,
PRIMARY KEY (id),
FOREIGN KEY (vendor_id) REFERENCES vendor_food (id),
FOREIGN KEY (customer_id) REFERENCES customers (id)
);