#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*|*MINGW*|*MSYS*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/python" ]; then
  "$basedir/python"  "$basedir/node_modules/casperjs/bin/casperjs" "$@"
  ret=$?
else 
  python  "$basedir/node_modules/casperjs/bin/casperjs" "$@"
  ret=$?
fi
exit $ret
