CREATE DATABASE foodbag;
USE foodbag;
SHOW TABLES;

CREATE TABLE customers (
	id INT NOT NULL AUTO_INCREMENT,	
	full_name VARCHAR(200) NOT NULL,
	email VARCHAR(40) NOT NULL,		
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
	PRIMARY KEY (id)
);
SELECT * FROM customers;
    