-- CREATE THE DATABASE FOR THE COMPANY
CREATE DATABASE transportation_company;

-- CHOOSE TO USE THE DATABASE CREATED ABOVE
USE transportation_company;

-- CREATE TABLE FOR PASSENGERS
CREATE TABLE passengers (
	id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(250) NOT NULL,
    sex VARCHAR(10) NOT NULL,
    age VARCHAR(50),
    PRIMARY KEY (id)
);

-- CREATE TABLE FOR TRIPS 
CREATE TABLE trips (
	id INT NOT NULL AUTO_INCREMENT,
    passengers_id INT NOT NULL,
    ticket VARCHAR(250) NOT NULL,
    fare DECIMAL(10, 2) NOT NULL,
    cabin VARCHAR(10),
    embarked VARCHAR(250) NOT NULL,
    class ENUM('1', '2', '3') NOT NULL,
    sibsp INT NOT NULL,
    parch INT NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (passengers_id) REFERENCES passengers (id)
);

-- CREATE TABLE FOR ACCIDENT SURVIVORS(ONLY USED IF AN ACCIDENT OCCURS
CREATE TABLE accident_cases (
	id INT NOT NULL AUTO_INCREMENT,
    passengers_id INT NOT NULL,
	survival BOOLEAN NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (passengers_id) REFERENCES passengers (id)
);
