 -- TO CREATE DATABASE CALLED FOODBAG
CREATE DATABASE foodbag;
-- TO CONFIRM IF DATABASE IS CREATED
SHOW DATABASES;
 -- TO USE THE FOODBAG DATABASE
USE foodbag;
 -- TO START CREATING THE FOOD TABLE
CREATE TABLE food (
id INT AUTO_INCREMENT NOT NULL,
type VARCHAR(255) NOT NULL,
PRIMARY KEY (id)
);

 -- TO START CREATING THE VENDORS TABLE
 CREATE TABLE vendors (
  id INT AUTO_INCREMENT NOT NULL,
  admin_id INT NOT NULL,
  food_id INT NOT NULL,
  name VARCHAR(255) NOT NULL,
  amount DECIMAL(10, 2) NOT NULL,
  PRIMARY KEY (id),
   -- THE COMMAND BELOW WILL LINK IT TO THE FOOD TABLE
   FOREIGN KEY (food_id) REFERENCES food (id)
 );
 
  -- NOW TO CREATING ADMIN TABLE
  CREATE TABLE admins (
	id INT AUTO_INCREMENT NOT NULL,
    name VARCHAR(255) NOT NULL,
    type INT NOT NULL,
    email_adrress VARCHAR(255) NOT NULL,
    phone_number INT NOT NULL,
    password VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
  );
  
  -- TO CREATING CUSTOMERS TABLE
  CREATE TABLE customers (
	id INT AUTO_INCREMENT NOT NULL,
    name VARCHAR (255) NOT NULL,
    phone_number INT NOT NULL,
    address VARCHAR (255) NOT NULL,
    payment_method VARCHAR (255),
    PRIMARY KEY (id)
);

-- TO CREATE THE ORDERS TABLE
CREATE TABLE orders (
	id INT AUTO_INCREMENT NOT NULL,
    vendors_id INT NOT NULL,
    customers_id INT NOT NULL,
    PRIMARY KEY (id),
    -- LINKING IT TO THE VENDORS AND CUSTOMERS TABLES
    FOREIGN KEY (vendors_id) REFERENCES vendors (id),
    FOREIGN KEY (customers_id) REFERENCES customers (id)
);