<?php
// Include config file
require_once "config.php";
echo "<h1> List of Customers </h1>";

// A cookie in PHP is a small file with a maximum size of 4KB that the web server stores on the client computer. They are typically used to keep track of information such as a username that the site can retrieve to personalize the page when the user visits the website next time.


$cookie_name = 'allCustomers';


// It is always advisable to check whether a cookie is set or not before accessing its value. Therefore to check whether a cookie is set or not, the PHP isset() function is used.

// 1. check if cookie exists
if(!isset($_COOKIE[$cookie_name])) {
    // 2. get cookie data
    $customersList = ($_COOKIE[$cookie_name]);
} else

    // 3. there is no cookie, load data from database
    $sql = "SELECT id, first_name, last_name, customer_email, created_at FROM customers";
    $result = $pdo->query($sql);
   //
    $customerList = $result->fetchAll();
    
    // Setting Cookie In PHP: To set a cookie in PHP, the setcookie() function is used. The setcookie() function needs to be called prior to any output generated by the script otherwise the cookie will not be set.
    //Note: The setcookie() function must appear BEFORE the <html> tag.
    
    //save in cookie
    // cookie will expire in 1 hour
    setcookie($cookie_name, ($result), time() + 3600, "/", 0);
    
    
// 4. displayresult using $result only
    if (!empty($result)){
        echo " <h2> Customer Details </h2>";
            echo '<table>';
                echo '<tr>';
                    echo "<th>S/N</th>";
                    echo "<th>First_Name</th>";
                    echo "<th>Last_Name</th>";
                    echo "<th>Customer_Email</th>";
                    echo "<th>Created_At</th>";
                    echo "<th>Actions</th>";
                echo "</tr>";
         /* PHP code to fetch data from rows.loop will iterate until all data is fetched */
            foreach($result as $rows){
                echo '<tr>';
                    echo "<td>" . $row['id'] . "</td>";
                    echo "<td>" . $row['first_name'] . "</td>";
                    echo "<td>" . $row['last_name'] . "</td>";
                    echo "<td>" . $row['customer_email'] . "</td>";
                    echo "<td>" . $row['created_at'] . "</td>";
                    echo "<td>" . "<a href='list-of-orders.php?id=$row[id]>$row[first_name]' class='view-btn'>View Order</a>" . "
                    </td>";
                echo '</tr>';
            }
            echo '</table>';

            //free result
            unset($customersList);
    }else {
        echo "No records from query were returned";
    }

 ?>


<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Customers Details</title>
    <!-- CSS FOR STYLING THE PAGE -->
    <style>
    table {
        margin: 0 auto;
        font-size: large;
        border: 1px solid black;
    }

    h1 {
        text-align: center;
        color: #006600;
        font-size: xx-large;
        font-family: 'Gill Sans', 'Gill Sans MT',
            ' Calibri', 'Trebuchet MS', 'sans-serif';
    }

    td {
        background-color: #E4F5D4;
        border: 1px solid black;
    }

    th,
    td {
        font-weight: bold;
        border: 1px solid black;
        padding: 10px;
        text-align: center;
    }

    td {
        font-weight: lighter;
    }

    .view-btn {
        color: black;
        background-color: #009432;
        font-weight: bold;
        padding: 0.5rem;
        font-size: medium;
        text-decoration: none;
    }

    .view-btn:hover {
        background: #006266;
    }
    </style>
</head>

<body>
</body>

</html>